name: GitHub Traffic Stats Backup

on:
  schedule:
    # מורץ אוטומטית כל יום בחצות
    - cron: '0 0 * * *'
  # מאפשר הרצה ידנית בלחיצת כפתור
  workflow_dispatch:

jobs:
  run-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and Save Traffic Stats
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ github.repository }}
          gh_token: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
          stats_branch: 'traffic'
